version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: tests
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: operator
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: operator
    schedule:
      interval: weekly
