---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pogocache-operator
  namespace: pogocache-system
  labels:
    app.kubernetes.io/name: pogocache-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: kustomize
